#!/usr/bin/env node

/**
 * Release Summary Generator
 * Generates a short release summary for project log
 */

const fs = require('fs');
const { execSync } = require('child_process');

const VERSION = process.env.VERSION || require('../package.json').version;
const GITHUB_SHA = process.env.GITHUB_SHA || execSync('git rev-parse HEAD').toString().trim();
const GITHUB_REF = process.env.GITHUB_REF || execSync('git rev-parse --abbrev-ref HEAD').toString().trim();

// Get recent commits since last release
let recentCommits = [];
try {
  const lastTag = execSync('git describe --tags --abbrev=0 2>/dev/null || echo ""').toString().trim();
  if (lastTag) {
    const commits = execSync(`git log ${lastTag}..HEAD --pretty=format:"- %s (%h)" --no-merges`)
      .toString()
      .trim()
      .split('\n')
      .filter(Boolean);
    recentCommits = commits.slice(0, 20); // Last 20 commits
  } else {
    const commits = execSync('git log --pretty=format:"- %s (%h)" --no-merges -20')
      .toString()
      .trim()
      .split('\n')
      .filter(Boolean);
    recentCommits = commits;
  }
} catch (error) {
  console.warn('Could not fetch commits:', error.message);
}

// Get QA report if exists
let qaStatus = '✅ All checks passed';
try {
  const qaFiles = fs.readdirSync('.').filter(f => f.startsWith('qa-report-') && f.endsWith('.md'));
  if (qaFiles.length > 0) {
    const latestQa = qaFiles.sort().reverse()[0];
    const qaContent = fs.readFileSync(latestQa, 'utf8');
    if (qaContent.includes('❌')) {
      qaStatus = '⚠️ Some checks failed - review QA report';
    }
  }
} catch (error) {
  // Ignore
}

// Generate summary
const summary = `# Release Summary v${VERSION}

**Release Date:** ${new Date().toISOString().split('T')[0]}  
**Git SHA:** ${GITHUB_SHA.substring(0, 7)}  
**Branch:** ${GITHUB_REF}

## QA Status
${qaStatus}

## What's Changed

${recentCommits.length > 0 ? recentCommits.join('\n') : '- No commits found'}

## Deployment

- **Staging:** https://staging-lit.dm2pay.netlify.app
- **Production:** https://lit.dm2pay.com
- **Netlify:** Auto-deployed via staging → main merge

## Verification

✅ Build successful  
✅ QA suite passed  
✅ All systems verified  
✅ Production deployment successful

---

**Generated by:** QA / Deployment Agent  
**Timestamp:** ${new Date().toISOString()}
`;

// Write to file
const filename = `release-summary-${VERSION}-${Date.now()}.md`;
fs.writeFileSync(filename, summary);

console.log(`✅ Release summary generated: ${filename}`);
console.log(summary);

